export default [
  {
    title: "STARTER",
    price: "₹3000/ 1 Month",
    facilities: [
      "GYM",
      "CARDIO",
      "AEROBIC",
      "DIET",
      "GROUP-TRAINING",
      "CROSSFIT",
      "YOGA",
      "ZUMBA",
      "STEAM",
      "SHOWER",
      "LOCKERS",
    ],
  },
  {
    title: "FIT",
    price: "₹5000/ 3 Month",
    facilities: [
      "GYM",
      "CARDIO",
      "AEROBIC",
      "DIET",
      "GROUP-TRAINING",
      "CROSSFIT",
      "YOGA",
      "ZUMBA",
      "STEAM",
      "SHOWER",
      "LOCKERS",
    ],
  },
  {
    title: "PRO",
    price: "₹7000/ 6 Month",
    facilities: [
      "GYM",
      "CARDIO",
      "AEROBIC",
      "DIET",
      "GROUP-TRAINING",
      "CROSSFIT",
      "YOGA",
      "ZUMBA",
      "STEAM",
      "SHOWER",
      "LOCKERS",
    ],
  },
  {
    title: "EXPERT",
    price: "₹10,000/ 12 Month",
    facilities: [
      "GYM",
      "CARDIO",
      "AEROBIC",
      "DIET",
      "GROUP-TRAINING",
      "CROSSFIT",
      "YOGA",
      "ZUMBA",
      "STEAM",
      "SHOWER",
      "LOCKERS",
    ],
  },
];
